### ISSUE TITLE
Notifications: First notification delay ignored

### ISSUE THREAD

**Issue by oragain** [centreon/centreon-engine#215]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Centreon Web version**: 
Centreon 19.04.2

**Centreon Engine version**: 
Centreon Engine 19.04.1

**Centreon Broker version**: 

**OS**: 
LSB Version:    :core-4.1-amd64:core-4.1-noarch:cxx-4.1-amd64:cxx-4.1-noarch:desktop-4.1-amd64:desktop-4.1-noarch:languages-4.1-amd64:languages-4.1-noarch:printing-4.1-amd64:printing-4.1-noarch
Distributor ID: CentOS
Description:    CentOS Linux release 7.6.1810 (Core)
Release:        7.6.1810
Codename:       Core

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Hyper-V 2016 Gen 2 VM

**Steps to reproduce the issue:**
1. Install out of the box
2. Configure a host and service
3. Add a notification delay

**Describe the results you received:**
Sometimes notifications are sent without regards of notification delay

**Describe the results you expected:**
Always wait for the first notification delay before sending notification

**Additional information you think important (e.g. issue happens only occasionally):**
Happens quite often, have yet to find a common denominator

**Comment by bouda1** [comment]
Hi,
We work on this bug and you should see very soon new versions of engine and broker that fix it.
Regards.

**Comment by bouda1** [comment]
We expect a beta version, next week. You are welcome to test it! ;-)

**Comment by SylvestreG** [comment]
Hi,

This issue should be fixed in 19.10. I will close this issue. Please re-open this issue if your problem comes back on 19.10.

Best Regards,

**Comment by oragain** [comment]
Hi,
The issue is still present.
Best regards,

**Comment by oragain** [comment]
My bad, i jumped the gun too soon. I'll reconfirm at a later time.
I have residual settings from past previous debugging sessions still in the system such as Max Check Attempts set to 1.

So the question is, shouldn't the system still wait 5 minutes to fire off a notification whatever the value of the Max Check Attempts ?

![centreon - first notification delay bug - email](https://user-images.githubusercontent.com/16800336/67424990-376fe600-f5a5-11e9-86e2-f91d126ace1a.PNG)
![centreon - first notification delay bug - service configuration](https://user-images.githubusercontent.com/16800336/67424991-376fe600-f5a5-11e9-9fb1-6590c061dcda.PNG)
![centreon - first notification delay bug](https://user-images.githubusercontent.com/16800336/67424992-376fe600-f5a5-11e9-8f7c-2215527155a3.PNG)
![centreon - first notification delay bug - service configuration main](https://user-images.githubusercontent.com/16800336/67424994-376fe600-f5a5-11e9-8af6-c0bb28017c75.PNG)

**Comment by oragain** [comment]
So, even setting Max Check Attempts to 2, the issue still is happening.
I get notifications as soon as the check goes critical

**Comment by oragain** [comment]
As a side note, trying to use 0 (default) in the max check attempts returns: 
Error while processing a config file: Parsing of object definition failed in file '/var/cache/centreon/config/engine/2/services.cfg' on line 4179: Invalid line 'max_check_attempts 0'

**Comment by lpinsivy** [comment]
Hi @oragain can you enable debug of Centreon Engine and check the /var/log/centreon-engine/centengine.debug file to know why the notification is sent without delay ?

**Comment by SylvestreG** [comment]
before sending us centengine.debug please, In the Engine configuration, click on the Debug tab and in the Debug Level field, activate the notification information. Then set the Debug Verbosity to "More detailed information". Save this configuration and restart engine.

**Comment by Tpo76** [comment]
Hi gents,

Here all the information you're looking for
[centengine.debug.txt](https://github.com/centreon/centreon-engine/files/3894070/centengine.debug.txt)

Please also find below the service definition in engine cfg file:
define service {
    host_name                      b-sv-prd-tra-01
    service_description            ITRANS - FrontEnd.SHA256 - Memory
    contact_groups                 Supervisors
    check_command                  0_OS-Windows-WMI-m-s-a-w-c
    check_period                   24x7
    notification_period            24x7
    max_check_attempts             2
    check_interval                 5
    retry_interval                 2
    notification_interval          60
    notification_options           c,c
    first_notification_delay       5
    stalking_options               o
    register                       1
    _WMIAUTH                       wmiauth
    _MODULE                        windows
    _SUBMODULE                     memservice
    _ARGS                          %FrontEnd.SHA256%
    _WARNING                       1000
    _CRITICAL                      2000
    _SERVICE_ID                    1432
}

**Comment by SylvestreG** [comment]
Fixed in 19.10.8
