### ISSUE TITLE
Error when Linking CXX executable centengine on Debian 9

### ISSUE THREAD

**Issue by ainiesta82** [centreon/centreon-engine#422]
Hi all. I am having trouble installing centreon-engine on a Debian 9 VM, encountering an error after running "make && make install". It stops at 95% Linking CXX executable centengine. Previously I had no trouble installing Centreon CLIB and I'm following all the instructions as they are described here. I attached the output of both the CMAKE and the MAKE INSTALL commands so that this can be looked into it. Thanks a lot. 

[centreon-engine-makeinstall.log](https://github.com/centreon/centreon-engine/files/5704577/centreon-engine-makeinstall.log)
[centreon-engine-cmake.log](https://github.com/centreon/centreon-engine/files/5704578/centreon-engine-cmake.log)

**Comment by bouda1** [comment]
Hi,

Could you try to open ~/.conan/profiles/default and change the line
compiler.libcxx=libstdc++ with compiler.libcxx=libstdc++11

Then, open the main CMakeLists.txt and change
add_definitions("-D_GLIBCXX_USE_CXX11_ABI=0") with add_definitions("-D_GLIBCXX_USE_CXX11_ABI=1")

Those changes are no more needed on the branch master and the cmake.sh script works better on that branch.

I will try to update the cmake.sh script so that compiling engine will be easier.
Cheers.

**Comment by ainiesta82** [comment]
Hi David,

I double checked that in fact I had the compiler set to **libstdc++11** on both conan and CMakeLists.txt but I got the same error. I got rid of the **build** folder and ran the script **cmake.sh** (without removing the conan config folder) but now is failing at 63% with the same error (See below output excerpt):

[ 63%] Linking CXX executable centengine
CMakeFiles/centengine.dir/src/main.cc.o: In function `main':
/usr/local/src/centreon-engine/src/main.cc:161: undefined reference to `com::centreon::io::directory_entry::current_path[abi:cxx11]()'
CMakeFiles/centengine.dir/src/main.cc.o: In function `com::centreon::logging::temp_logger& com::centreon::logging::temp_logger::operator<< <std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >)':
/usr/include/com/centreon/logging/temp_logger.hh:50: undefined reference to `com::centreon::misc::stringifier::operator<<(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'

Any other ideas/suggestions? Thanks in advance. 
Best,
Angel

**Comment by bouda1** [comment]
Your errors are always around the same issue but not at the same place.
Could you check that centreon-clib has been compiled using the c++11 abi?

Check the CMakeLists.txt file to be sure.
Then you can remove the build directory, launch the cmake.sh script and then compile and install again.

Then in centreon-engine, you can try again.

You are not so far of the result, and your error is typical of a C++ abi change...
Cheers.

**Comment by ainiesta82** [comment]
David, unfortunately I followed your suggestions without success. I checked the centreon-clib and it was compiled with the wrong compiler, but I recompiled it and reinstalled it with the c++11 abi, and afterwards tried again with centreon-engine but it's failing on exactly the same. It's really frustrating not being able to find out what is going on here...

**Comment by bouda1** [comment]
I work everyday on engine and broker on  a Debian platform. So I promess they compile :smile: 

The CMakeLists.txt files are tuned to be compiled on Centos7, that's why we have several things to change here and there.

I check from a new machine, so I will be able to tell you what's going wrong.

**Comment by ainiesta82** [comment]
I trust you but on my machine it doesn't... It's a pity because I really wanted to give a go to Centreon (and perhaps migrate a current Nagios setup to Centreon), but I can't move forward if it can't be installed via source code. And I don't consider using Centos anymore as RHEL already mentioned that the project is dead as of Dec. 2021.

**Comment by bouda1** [comment]
Can you confirm your compiler to be gcc6 ?

**Comment by bouda1** [comment]
So I have started a new Debian 9 machine (usually I work on Debian10). I saw the compiler is gcc6 and realized that the conan packages we provide from our repository are not compiled for that gcc version. So I pushed the binaries compiled with gcc6 to the repo. Now, it should be quick and easy to update them if we use this compiler (from the centreon-engine directory):

`rm -rf build`
`./cmake.sh`
`cd build`
`conan remote add centreon https://api.bintray.com/conan/centreon/centreon`
`conan install .. -r centreon`
make -j4
make install

Let's hope this will be good this time :crossed_fingers:

**Comment by ainiesta82** [comment]
> Can you confirm your compiler to be gcc6 ?

Yes it is gcc6.

**Comment by ainiesta82** [comment]
> conan install .. -r centreon

**Comment by ainiesta82** [comment]
Followed your suggestions and still failing. Please see attached make command output. Thanks. 
`root@cougar-devel:/usr/local/src/centreon-engine/build# make -j4
[  0%] Generating ../../../src/simumod/neb.cc
[  1%] Generating interface files of the proto file (protobuf)
Scanning dependencies of target centenginestats
Scanning dependencies of target cce_core
[  1%] Building CXX object CMakeFiles/centenginestats.dir/src/centenginestats.cc.o
Scanning dependencies of target simumod
[  2%] Building CXX object src/simumod/CMakeFiles/simumod.dir/neb.cc.o
Scanning dependencies of target cerpc
[  2%] Building CXX object enginerpc/CMakeFiles/cerpc.dir/engine.grpc.pb.cc.o
[  3%] Building CXX object CMakeFiles/cce_core.dir/src/anomalydetection.cc.o
[  3%] Linking CXX shared library simumod.so
[  3%] Linking CXX executable centenginestats
[  3%] Built target simumod
[  3%] Building CXX object CMakeFiles/cce_core.dir/src/broker.cc.o
[  3%] Built target centenginestats
Scanning dependencies of target externalcmd
In file included from /root/.conan/data/grpc/1.27.3/inexorgame/stable/package/808c19628b2a2c25bfca971d2b945ea8aa53c235/include/grpcpp/impl/codegen/config_protobuf.h:50:0,
                 from /root/.conan/data/grpc/1.27.3/inexorgame/stable/package/808c19628b2a2c25bfca971d2b945ea8aa53c235/include/grpcpp/impl/codegen/proto_utils.h:28,
                 from /usr/local/src/centreon-engine/enginerpc/engine.grpc.pb.h:19,
                 from /usr/local/src/centreon-engine/enginerpc/engine.grpc.pb.cc:6:
/root/.conan/data/protobuf/3.9.1/bincrafters/stable/package/d0ec62fc032e5a10524fa454546aa1bdbb22baf8/include/google/protobuf/descriptor_database.h: In member function ‘virtual bool google::protobuf::DescriptorDatabase::FindAllFileNames(std::vector<std::__cxx11::basic_string<char> >*)’:
/root/.conan/data/protobuf/3.9.1/bincrafters/stable/package/d0ec62fc032e5a10524fa454546aa1bdbb22baf8/include/google/protobuf/descriptor_database.h:119:59: warning: unused parameter ‘output’ [-Wunused-parameter]
   virtual bool FindAllFileNames(std::vector<std::string>* output) {
                                                           ^~~~~~
[  4%] Building CXX object modules/external_commands/CMakeFiles/externalcmd.dir/src/commands.cc.o
In file included from /root/.conan/data/protobuf/3.9.1/bincrafters/stable/package/d0ec62fc032e5a10524fa454546aa1bdbb22baf8/include/google/protobuf/util/json_util.h:38:0,
                 from /root/.conan/data/grpc/1.27.3/inexorgame/stable/package/808c19628b2a2c25bfca971d2b945ea8aa53c235/include/grpcpp/impl/codegen/config_protobuf.h:67,
                 from /root/.conan/data/grpc/1.27.3/inexorgame/stable/package/808c19628b2a2c25bfca971d2b945ea8aa53c235/include/grpcpp/impl/codegen/proto_utils.h:28,
                 from /usr/local/src/centreon-engine/enginerpc/engine.grpc.pb.h:19,
                 from /usr/local/src/centreon-engine/enginerpc/engine.grpc.pb.cc:6:
/root/.conan/data/protobuf/3.9.1/bincrafters/stable/package/d0ec62fc032e5a10524fa454546aa1bdbb22baf8/include/google/protobuf/stubs/bytestream.h: In member function ‘virtual void google::protobuf::strings::NullByteSink::Append(const char*, size_t)’:
/root/.conan/data/protobuf/3.9.1/bincrafters/stable/package/d0ec62fc032e5a10524fa454546aa1bdbb22baf8/include/google/protobuf/stubs/bytestream.h:277:35: warning: unused parameter ‘data’ [-Wunused-parameter]
   virtual void Append(const char *data, size_t n) override {}
                                   ^~~~
/root/.conan/data/protobuf/3.9.1/bincrafters/stable/package/d0ec62fc032e5a10524fa454546aa1bdbb22baf8/include/google/protobuf/stubs/bytestream.h:277:48: warning: unused parameter ‘n’ [-Wunused-parameter]
   virtual void Append(const char *data, size_t n) override {}
                                                ^
[  4%] Building CXX object CMakeFiles/cce_core.dir/src/checkable.cc.o
[  5%] Building CXX object CMakeFiles/cce_core.dir/src/check_result.cc.o
/usr/local/src/centreon-engine/modules/external_commands/src/commands.cc: In function ‘int cmd_add_comment(int, time_t, char*)’:
/usr/local/src/centreon-engine/modules/external_commands/src/commands.cc:182:12: warning: unused variable ‘host_id’ [-Wunused-variable]
   uint64_t host_id = 0;
            ^~~~~~~
/usr/local/src/centreon-engine/modules/external_commands/src/commands.cc: At global scope:
/usr/local/src/centreon-engine/modules/external_commands/src/commands.cc:238:47: warning: ‘maybe_unused’ attribute directive ignored [-Wattributes]
 int cmd_delete_comment(int cmd [[maybe_unused]], char* args) {
                                               ^
/usr/local/src/centreon-engine/modules/external_commands/src/commands.cc: In function ‘int cmd_delete_comment(int, char*)’:
/usr/local/src/centreon-engine/modules/external_commands/src/commands.cc:238:47: warning: unused parameter ‘cmd’ [-Wunused-parameter]
[  5%] Building CXX object CMakeFiles/cce_core.dir/src/command_manager.cc.o
[  6%] Building CXX object enginerpc/CMakeFiles/cerpc.dir/engine.pb.cc.o
[  7%] Building CXX object CMakeFiles/cce_core.dir/src/comment.cc.o
[  7%] Building CXX object modules/external_commands/CMakeFiles/externalcmd.dir/src/internal.cc.o
[  7%] Building CXX object CMakeFiles/cce_core.dir/src/config.cc.o
[  8%] Building CXX object CMakeFiles/cce_core.dir/src/contact.cc.o
[  8%] Linking CXX static library libcerpc.a
[  9%] Building CXX object modules/external_commands/CMakeFiles/externalcmd.dir/src/main.cc.o
[  9%] Built target cerpc
Scanning dependencies of target bench_passive_module
[  9%] Building CXX object modules/bench/CMakeFiles/bench_passive_module.dir/passive/module.cc.o
[  9%] Building CXX object CMakeFiles/cce_core.dir/src/contactgroup.cc.o
[  9%] Building CXX object modules/external_commands/CMakeFiles/externalcmd.dir/src/processing.cc.o
[  9%] Building CXX object CMakeFiles/cce_core.dir/src/customvariable.cc.o
[  9%] Linking CXX shared library bench_passive_module.so
[  9%] Built target bench_passive_module
Scanning dependencies of target centengine_bench_passive
[ 10%] Building CXX object CMakeFiles/cce_core.dir/src/daterange.cc.o
[ 11%] Building CXX object modules/bench/CMakeFiles/centengine_bench_passive.dir/passive/engine_cfg.cc.o
[ 11%] Building CXX object modules/bench/CMakeFiles/centengine_bench_passive.dir/passive/main.cc.o
[ 11%] Building CXX object modules/external_commands/CMakeFiles/externalcmd.dir/src/utils.cc.o
[ 11%] Building CXX object CMakeFiles/cce_core.dir/src/dependency.cc.o
[ 12%] Linking CXX executable centengine_bench_passive
CMakeFiles/centengine_bench_passive.dir/passive/engine_cfg.cc.o: In function `engine_cfg::engine_cfg(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, int, int, int, int, int, bool)':
/usr/local/src/centreon-engine/modules/bench/passive/engine_cfg.cc:50: warning: the use of `tmpnam' is dangerous, better use `mkstemp'
CMakeFiles/centengine_bench_passive.dir/passive/main.cc.o: In function `main':
/usr/local/src/centreon-engine/modules/bench/passive/main.cc:139: undefined reference to `com::centreon::process::exec(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, unsigned int)'
collect2: error: ld returned 1 exit status
modules/bench/CMakeFiles/centengine_bench_passive.dir/build.make:121: recipe for target 'modules/bench/centengine_bench_passive' failed
make[2]: *** [modules/bench/centengine_bench_passive] Error 1
CMakeFiles/Makefile2:584: recipe for target 'modules/bench/CMakeFiles/centengine_bench_passive.dir/all' failed
make[1]: *** [modules/bench/CMakeFiles/centengine_bench_passive.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 13%] Building CXX object CMakeFiles/cce_core.dir/src/diagnostic.cc.o
[ 13%] Building CXX object CMakeFiles/cce_core.dir/src/exceptions/error.cc.o
[ 13%] Building CXX object CMakeFiles/cce_core.dir/src/flapping.cc.o
[ 14%] Building CXX object CMakeFiles/cce_core.dir/src/escalation.cc.o
[ 15%] Linking CXX shared library externalcmd.so
[ 15%] Built target externalcmd
[ 15%] Building CXX object CMakeFiles/cce_core.dir/src/globals.cc.o
[ 16%] Building CXX object CMakeFiles/cce_core.dir/src/host.cc.o
[ 16%] Building CXX object CMakeFiles/cce_core.dir/src/hostdependency.cc.o
[ 17%] Building CXX object CMakeFiles/cce_core.dir/src/hostescalation.cc.o
[ 17%] Building CXX object CMakeFiles/cce_core.dir/src/hostgroup.cc.o
[ 17%] Building CXX object CMakeFiles/cce_core.dir/src/macros.cc.o
[ 18%] Building CXX object CMakeFiles/cce_core.dir/src/nebmods.cc.o
[ 18%] Building CXX object CMakeFiles/cce_core.dir/src/notification.cc.o
[ 19%] Building CXX object CMakeFiles/cce_core.dir/src/notifier.cc.o
[ 19%] Building CXX object CMakeFiles/cce_core.dir/src/sehandlers.cc.o
[ 20%] Building CXX object CMakeFiles/cce_core.dir/src/service.cc.o
[ 20%] Building CXX object CMakeFiles/cce_core.dir/src/servicedependency.cc.o
[ 20%] Building CXX object CMakeFiles/cce_core.dir/src/serviceescalation.cc.o
[ 21%] Building CXX object CMakeFiles/cce_core.dir/src/servicegroup.cc.o
[ 21%] Building CXX object CMakeFiles/cce_core.dir/src/shared.cc.o
[ 22%] Building CXX object CMakeFiles/cce_core.dir/src/statistics.cc.o
[ 22%] Building CXX object CMakeFiles/cce_core.dir/src/statusdata.cc.o
[ 22%] Building CXX object CMakeFiles/cce_core.dir/src/string.cc.o
[ 23%] Building CXX object CMakeFiles/cce_core.dir/src/timeperiod.cc.o
[ 23%] Building CXX object CMakeFiles/cce_core.dir/src/timerange.cc.o
[ 24%] Building CXX object CMakeFiles/cce_core.dir/src/timezone_locker.cc.o
[ 24%] Building CXX object CMakeFiles/cce_core.dir/src/timezone_manager.cc.o
[ 25%] Building CXX object CMakeFiles/cce_core.dir/src/utils.cc.o
[ 25%] Building CXX object CMakeFiles/cce_core.dir/src/xpddefault.cc.o
[ 25%] Building CXX object CMakeFiles/cce_core.dir/src/xsddefault.cc.o
[ 26%] Building CXX object CMakeFiles/cce_core.dir/src/broker/compatibility.cc.o
[ 26%] Building CXX object CMakeFiles/cce_core.dir/src/broker/loader.cc.o
[ 27%] Building CXX object CMakeFiles/cce_core.dir/src/broker/handle.cc.o
[ 27%] Building CXX object CMakeFiles/cce_core.dir/src/checks/checker.cc.o
[ 28%] Building CXX object CMakeFiles/cce_core.dir/src/checks/stats.cc.o
[ 28%] Building CXX object CMakeFiles/cce_core.dir/src/downtimes/downtime.cc.o
[ 28%] Building CXX object CMakeFiles/cce_core.dir/src/downtimes/downtime_manager.cc.o
[ 29%] Building CXX object CMakeFiles/cce_core.dir/src/downtimes/host_downtime.cc.o
[ 29%] Building CXX object CMakeFiles/cce_core.dir/src/downtimes/service_downtime.cc.o
[ 30%] Building CXX object CMakeFiles/cce_core.dir/src/downtimes/downtime_finder.cc.o
[ 30%] Building CXX object CMakeFiles/cce_core.dir/src/configuration/applier/anomalydetection.cc.o
/usr/local/src/centreon-engine/src/downtimes/downtime_finder.cc: In member function ‘com::centreon::engine::downtimes::downtime_finder::result_set com::centreon::engine::downtimes::downtime_finder::find_matching_all(const criteria_set&)’:
/usr/local/src/centreon-engine/src/downtimes/downtime_finder.cc:82:14: warning: enumeration value ‘any_downtime’ not handled in switch [-Wswitch]
       switch (dt.second->get_type()) {
              ^
[ 30%] Building CXX object CMakeFiles/cce_core.dir/src/configuration/applier/command.cc.o
[ 31%] Building CXX object CMakeFiles/cce_core.dir/src/configuration/applier/connector.cc.o
[ 31%] Building CXX object CMakeFiles/cce_core.dir/src/configuration/applier/contact.cc.o
[ 33%] Building CXX object CMakeFiles/cce_core.dir/src/configuration/applier/contactgroup.cc.o
[ 32%] Building CXX object CMakeFiles/cce_core.dir/src/configuration/applier/host.cc.o
[ 33%] Building CXX object CMakeFiles/cce_core.dir/src/configuration/applier/hostdependency.cc.o
[ 33%] Building CXX object CMakeFiles/cce_core.dir/src/configuration/applier/hostescalation.cc.o
[ 35%] Building CXX object CMakeFiles/cce_core.dir/src/configuration/applier/macros.cc.o
[ 35%] Building CXX object CMakeFiles/cce_core.dir/src/configuration/applier/logging.cc.o
[ 35%] Building CXX object CMakeFiles/cce_core.dir/src/configuration/applier/hostgroup.cc.o
[ 35%] Building CXX object CMakeFiles/cce_core.dir/src/configuration/applier/globals.cc.o
[ 35%] Building CXX object CMakeFiles/cce_core.dir/src/configuration/applier/scheduler.cc.o
[ 35%] Building CXX object CMakeFiles/cce_core.dir/src/configuration/applier/service.cc.o
[ 36%] Building CXX object CMakeFiles/cce_core.dir/src/configuration/applier/servicedependency.cc.o
[ 36%] Building CXX object CMakeFiles/cce_core.dir/src/configuration/applier/serviceescalation.cc.o
[ 37%] Building CXX object CMakeFiles/cce_core.dir/src/configuration/anomalydetection.cc.o
[ 37%] Building CXX object CMakeFiles/cce_core.dir/src/configuration/applier/timeperiod.cc.o
[ 37%] Building CXX object CMakeFiles/cce_core.dir/src/configuration/applier/state.cc.o
[ 38%] Building CXX object CMakeFiles/cce_core.dir/src/configuration/applier/servicegroup.cc.o
[ 38%] Building CXX object CMakeFiles/cce_core.dir/src/configuration/command.cc.o
[ 39%] Building CXX object CMakeFiles/cce_core.dir/src/configuration/connector.cc.o
[ 39%] Building CXX object CMakeFiles/cce_core.dir/src/configuration/contact.cc.o
[ 40%] Building CXX object CMakeFiles/cce_core.dir/src/configuration/contactgroup.cc.o
[ 40%] Building CXX object CMakeFiles/cce_core.dir/src/configuration/daterange.cc.o
[ 41%] Building CXX object CMakeFiles/cce_core.dir/src/configuration/group.cc.o
[ 41%] Building CXX object CMakeFiles/cce_core.dir/src/configuration/host.cc.o
[ 41%] Building CXX object CMakeFiles/cce_core.dir/src/configuration/hostdependency.cc.o
[ 42%] Building CXX object CMakeFiles/cce_core.dir/src/configuration/hostescalation.cc.o
[ 42%] Building CXX object CMakeFiles/cce_core.dir/src/configuration/hostextinfo.cc.o
[ 43%] Building CXX object CMakeFiles/cce_core.dir/src/configuration/hostgroup.cc.o
[ 43%] Building CXX object CMakeFiles/cce_core.dir/src/configuration/object.cc.o
[ 43%] Building CXX object CMakeFiles/cce_core.dir/src/configuration/parser.cc.o
[ 44%] Building CXX object CMakeFiles/cce_core.dir/src/configuration/point_2d.cc.o
[ 44%] Building CXX object CMakeFiles/cce_core.dir/src/configuration/point_3d.cc.o
[ 45%] Building CXX object CMakeFiles/cce_core.dir/src/configuration/state.cc.o
[ 45%] Building CXX object CMakeFiles/cce_core.dir/src/configuration/service.cc.o
[ 46%] Building CXX object CMakeFiles/cce_core.dir/src/configuration/servicedependency.cc.o
[ 46%] Building CXX object CMakeFiles/cce_core.dir/src/configuration/serviceescalation.cc.o
[ 46%] Building CXX object CMakeFiles/cce_core.dir/src/configuration/serviceextinfo.cc.o
[ 47%] Building CXX object CMakeFiles/cce_core.dir/src/configuration/servicegroup.cc.o
[ 47%] Building CXX object CMakeFiles/cce_core.dir/src/configuration/timeperiod.cc.o
[ 48%] Building CXX object CMakeFiles/cce_core.dir/src/configuration/timerange.cc.o
[ 48%] Building CXX object CMakeFiles/cce_core.dir/src/commands/command.cc.o
[ 49%] Building CXX object CMakeFiles/cce_core.dir/src/commands/connector.cc.o
[ 49%] Building CXX object CMakeFiles/cce_core.dir/src/commands/environment.cc.o
[ 49%] Building CXX object CMakeFiles/cce_core.dir/src/commands/forward.cc.o
[ 50%] Building CXX object CMakeFiles/cce_core.dir/src/commands/raw.cc.o
[ 50%] Building CXX object CMakeFiles/cce_core.dir/src/commands/result.cc.o
[ 51%] Building CXX object CMakeFiles/cce_core.dir/src/compatibility/common.cc.o
[ 51%] Building CXX object CMakeFiles/cce_core.dir/src/compatibility/embedded_perl.cc.o
[ 51%] Building CXX object CMakeFiles/cce_core.dir/src/compatibility/globals.cc.o
[ 52%] Building CXX object CMakeFiles/cce_core.dir/src/compatibility/logging.cc.o
[ 52%] Building CXX object CMakeFiles/cce_core.dir/src/compatibility/mmap.cc.o
[ 53%] Building CXX object CMakeFiles/cce_core.dir/src/compatibility/sighandlers.cc.o
[ 53%] Building CXX object CMakeFiles/cce_core.dir/src/compatibility/utils.cc.o
[ 54%] Building CXX object CMakeFiles/cce_core.dir/src/events/loop.cc.o
[ 54%] Building CXX object CMakeFiles/cce_core.dir/src/events/sched_info.cc.o
[ 54%] Building CXX object CMakeFiles/cce_core.dir/src/events/timed_event.cc.o
[ 55%] Building CXX object CMakeFiles/cce_core.dir/src/logging/broker.cc.o
[ 55%] Building CXX object CMakeFiles/cce_core.dir/src/logging/debug_file.cc.o
[ 56%] Building CXX object CMakeFiles/cce_core.dir/src/macros/clear_host.cc.o
[ 56%] Building CXX object CMakeFiles/cce_core.dir/src/macros/clear_hostgroup.cc.o
[ 57%] Building CXX object CMakeFiles/cce_core.dir/src/macros/clear_service.cc.o
[ 57%] Building CXX object CMakeFiles/cce_core.dir/src/macros/clear_servicegroup.cc.o
[ 57%] Building CXX object CMakeFiles/cce_core.dir/src/macros/grab_host.cc.o
[ 58%] Building CXX object CMakeFiles/cce_core.dir/src/macros/grab_service.cc.o
[ 58%] Building CXX object CMakeFiles/cce_core.dir/src/macros/grab_value.cc.o
[ 59%] Building CXX object CMakeFiles/cce_core.dir/src/macros/misc.cc.o
/usr/local/src/centreon-engine/src/macros/grab_value.cc: In function ‘int handle_contactgroup_macro(nagios_macros*, int, const string&, const string&, std::__cxx11::string&, int*)’:
/usr/local/src/centreon-engine/src/macros/grab_value.cc:379:53: warning: unused parameter ‘mac’ [-Wunused-parameter]
 static int handle_contactgroup_macro(nagios_macros* mac,
                                                     ^~~
[ 59%] Building CXX object CMakeFiles/cce_core.dir/src/macros/process.cc.o
[ 59%] Building CXX object CMakeFiles/cce_core.dir/src/retention/applier/comment.cc.o
[ 60%] Building CXX object CMakeFiles/cce_core.dir/src/retention/applier/contact.cc.o
[ 60%] Building CXX object CMakeFiles/cce_core.dir/src/retention/applier/downtime.cc.o
[ 61%] Building CXX object CMakeFiles/cce_core.dir/src/retention/applier/host.cc.o
[ 61%] Building CXX object CMakeFiles/cce_core.dir/src/retention/applier/program.cc.o
[ 62%] Building CXX object CMakeFiles/cce_core.dir/src/retention/applier/service.cc.o
[ 62%] Building CXX object CMakeFiles/cce_core.dir/src/retention/applier/state.cc.o
[ 62%] Building CXX object CMakeFiles/cce_core.dir/src/retention/applier/utils.cc.o
[ 63%] Building CXX object CMakeFiles/cce_core.dir/src/retention/comment.cc.o
[ 63%] Building CXX object CMakeFiles/cce_core.dir/src/retention/contact.cc.o
[ 64%] Building CXX object CMakeFiles/cce_core.dir/src/retention/downtime.cc.o
[ 64%] Building CXX object CMakeFiles/cce_core.dir/src/retention/dump.cc.o
[ 64%] Building CXX object CMakeFiles/cce_core.dir/src/retention/host.cc.o
[ 65%] Building CXX object CMakeFiles/cce_core.dir/src/retention/info.cc.o
[ 65%] Building CXX object CMakeFiles/cce_core.dir/src/retention/parser.cc.o
[ 66%] Building CXX object CMakeFiles/cce_core.dir/src/retention/program.cc.o
[ 66%] Building CXX object CMakeFiles/cce_core.dir/src/retention/object.cc.o
[ 67%] Building CXX object CMakeFiles/cce_core.dir/src/retention/service.cc.o
[ 67%] Building CXX object CMakeFiles/cce_core.dir/src/retention/state.cc.o
[ 67%] Linking CXX static library libcce_core.a
[ 67%] Built target cce_core
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2
`

**Comment by bouda1** [comment]
Is it possible that you have installed two versions of centreon_clib and when engine is compiled, it tries to link with the bad version of centreon_clib.
I'm curious about the result of `find /usr -name '*centreon_clib.so'`

Otherwise, I'm improving the cmake.sh scripts for each component. I hope they will be ready at the end of this day.

**Comment by ainiesta82** [comment]
@bouda1, that was the issue. 

I had installed in the beginning CLIB for 32 bit (lib /usr/lib/libcentreon_clib.so) instead of for 64bit architecture (lib /usr/lib64/libcentreon_clib.so) and forgot to remove the old one. But even using the script it was failing, so I edited by adding to the cmake command the flag **-DWITH_CENTREON_CLIB_LIBRARIES=/usr/lib64/libcentreon_clib.so** and it is all good now. You should definitely improve the script so that it detects automatically the right architecture and therefore selects the right clib for compilation, as having two clib versions installed shouldn't be an issue when installing centreon-engine. Thanks a lot for your help. I'm hoping that I'll not have similar issues with centreon-broker and centreon-web compilations.

Best,

Angel

**Comment by ainiesta82** [comment]
Also, there is something that I don't understand. Why do you guys use a **SysVinit** based script (init.d) for centreon-engine when **Systemd** is being used instead since Debian Jessie?

**Comment by bouda1** [comment]
Good to know for your issue.
In fact, centreon is quite big. Here you can find the sysvinit scripts but they are no more used except when we use them in docker I guess. We have a centreon-build repo that makes rpm files and generates also systemd files. But I think it is not public.

**Comment by ainiesta82** [comment]
> Good to know for your issue.
> In fact, centreon is quite big. Here you can find the sysvinit scripts but they are no more used except when we use them in docker I guess. We have a centreon-build repo that makes rpm files and generates also systemd files. But I think it is not public.

I see. Have you guys considered creating a deb package for centreon in a near future? It'd definitely make things easier... I am guessing that distros like SLES and Debian will become more popular now that CentOS project is dead...
